import json
import logging
import random
import math
from typing import TYPE_CHECKING, Dict, Any, List, Set, Optional
from ...utils.perf import metric_logger

# Import GossipProtocol
from .gossip_protocol import GossipProtocol

if TYPE_CHECKING:
    from ...core.node import Node

class CollaborationModule:
    """Handles alarm spreading (using Gossip) and receiving logic for a node.

    Responsible for disseminating alarms generated by the node to a subset of 
    neighbors using a Gossip protocol, and for processing alarms received from 
    other nodes, including trust verification and potential forwarding.

    Attributes:
        node (Node): The node instance that owns this module.
        logger (logging.Logger): Logger instance specific to this module.
        gossip (GossipProtocol): Instance of the gossip protocol implementation.
        received_alarm_ids (Set[str]): Set of IDs of alarms already received/processed 
                                       by this node to prevent loops and redundant processing.
    """

    def __init__(self, node: 'Node', feature_config: Optional[Dict[str, Any]] = None, trust_method_name: str = 'unknown'):
        """Initialize CollaborationModule, storing trust method name for conditional logic."""
        self.node = node
        self.logger = logging.getLogger(f"CollabModule-Node{self.node.id}")
        self.trust_method_name = trust_method_name # <-- Simpan nama metode trust
        node_rng = getattr(node, 'rng', None)
        self.rng = node_rng if node_rng is not None else random.Random(int(getattr(node, 'id', 0) or 0))
        feature_cfg = dict(feature_config or {})
        
        # Inisialisasi Gossip Protocol menggunakan parameter dari config
        gossip_fanout = feature_cfg.get('gossip_fanout', None)
        if gossip_fanout in (None, "sqrt", "sqrtN", "sqrt_n"):
            total_nodes = int(feature_cfg.get('total_nodes', 1))
            gossip_fanout = max(1, int(math.sqrt(max(1, total_nodes))))
        try:
            gossip_fanout = int(gossip_fanout)
        except Exception:
            gossip_fanout = 3
        gossip_max_hops = feature_cfg.get('gossip_max_hops', 5)
        self.gossip = GossipProtocol(fanout=gossip_fanout, rng=self.rng)
        self.gossip.max_hops = gossip_max_hops
        self.logger.debug(f"Gossip initialized with fanout={gossip_fanout}, max_hops={gossip_max_hops}. Trust Method: {self.trust_method_name}")
        
        self.received_alarm_ids: Set[str] = set()

    def spread_alarm(self, original_alarm: Dict[str, Any]):
        """Spread alarm variations using the CIDSeeks privacy-enhanced workflow."""

        self.logger.debug("Using advanced privacy/spreading for 3-level-challenge method.")
        privacy_module = getattr(self.node, 'privacy_module', None)
        if not privacy_module:
            self.logger.error(f"Privacy module not found for Node {self.node.id}, cannot generate variations.")
            return

        try:
            alarm_variations = privacy_module.generate_alarm_variations(original_alarm)
        except Exception as e:
            self.logger.error(f"Error generating alarm variations: {e}")
            return

        if not alarm_variations:
            self.logger.warning(f"No alarm variations generated for alarm {original_alarm.get('message_id')}")
            return

        original_hash = alarm_variations[0].get('original_alarm_hash', 'unknown_hash')
        self.logger.info(
            "Spreading %s variations for original alarm hash %s...",
            len(alarm_variations),
            original_hash[:8],
        )

        self.rng.shuffle(alarm_variations)

        neighbor_nodes: List['Node'] = self.node.neighbors
        valid_neighbors = [n for n in neighbor_nodes if hasattr(n, 'collaboration_module')]
        if not valid_neighbors:
            self.logger.warning(f"Node {self.node.id} has no valid neighbors to send alarm variations to.")
            return

        self.rng.shuffle(valid_neighbors)

        num_variations = len(alarm_variations)
        num_targets = min(num_variations, len(valid_neighbors))
        target_nodes = valid_neighbors[:num_targets]

        for i in range(num_targets):
            variation_to_send = alarm_variations[i]
            target_node = target_nodes[i]

            min_delay = self.node.feature_config.get('min_alarm_send_delay', 0.1) if hasattr(self.node, 'feature_config') else 0.1
            max_delay = self.node.feature_config.get('max_alarm_send_delay', 0.5) if hasattr(self.node, 'feature_config') else 0.5
            delay = self.rng.uniform(min_delay, max_delay)

            self.node.env.process(
                self._send_single_alarm_variation(variation_to_send, target_node, delay)
            )

        self.logger.debug(f"Scheduled sending of {num_targets} alarm variations with random delays (advanced path).")

    def _send_single_alarm_variation(self, alarm_variation: Dict[str, Any], target_node: 'Node', delay: float):
         """SimPy process to send a single alarm variation after a delay."""
         try:
             # 1. Wait for the delay
             yield self.node.env.timeout(delay)
             
             # 2. Authenticate
             self.logger.debug(f"Attempting delayed send of variation {alarm_variation.get('variation_sequence_number')} (hash: {alarm_variation.get('original_alarm_hash', 'N/A')[:8]}) to Node {target_node.id} after {delay:.2f} delay.")
             if self.node.authenticate(target_node):
                 # 3. Send if authenticated
                 target_collab_module = getattr(target_node, 'collaboration_module')
                 if target_collab_module:
                      # Increment hop count before sending
                      alarm_variation['gossip_hops'] = alarm_variation.get('gossip_hops', 0) + 1
                      # Log PMFA/DMPO send metadata with delay and receiver
                      try:
                          payload_size = len(str({
                              'current_destination_ip': alarm_variation.get('current_destination_ip'),
                              'current_port': alarm_variation.get('current_port'),
                              'current_msg': alarm_variation.get('current_msg'),
                          }).encode('utf-8'))
                          metric_logger.log_privacy_event({
                              'delay_ms': float(delay) * 1000.0,
                              'payload_size': payload_size,
                              'variant_id': alarm_variation.get('variation_sequence_number'),
                              'is_challenge': False,
                              'dmpo_enabled': bool(alarm_variation.get('dmpo_enabled', True)),
                              'sender_id': self.node.id,
                              'receiver_id': target_node.id,
                              'iteration': getattr(self.node, 'current_iteration', 0),
                              'message_id': alarm_variation.get('message_id'),
                              'alarm_hash': alarm_variation.get('original_alarm_hash'),
                          })
                      except Exception:
                          self.logger.debug("Failed to log privacy event", exc_info=True)
                      payload_bytes = len(json.dumps(alarm_variation).encode('utf-8'))
                      metric_logger.log_message(
                          iteration=getattr(self.node, 'current_iteration', 0),
                          sender_id=self.node.id,
                          receiver_id=target_node.id,
                          message_type='alarm_variation',
                          direction='out',
                          payload_bytes=payload_bytes,
                          latency_ms=float(delay) * 1000.0,
                          metadata={'strategy': 'advanced'},
                      )
                      target_collab_module.receive_alarm(alarm_variation, self.node)
                      self.logger.info(f"Sent variation {alarm_variation.get('variation_sequence_number')} to Node {target_node.id}.")
                 else:
                      self.logger.error(f"Target Node {target_node.id} missing collaboration module during delayed send.")
             else:
                 self.logger.debug(f"Authentication failed for delayed send to Node {target_node.id}.")
                 # Simpan event auth gagal jika perlu
                 if self.node.db:
                     self.node.db.store_event(
                         timestamp=self.node.env.now,
                         iteration=self.node.current_iteration,
                         node_id=self.node.id,
                         event_type='auth_failed_delayed_send',
                         details={'alarm_hash': alarm_variation.get('original_alarm_hash'), 
                                  'variation_seq': alarm_variation.get('variation_sequence_number')},
                         related_node_id=target_node.id
                     )
                     
         except Exception as e:
             self.logger.error(f"Error in _send_single_alarm_variation to Node {target_node.id}: {e}")
             import traceback
             self.logger.error(traceback.format_exc())

    def receive_alarm(self, alarm: Dict[str, Any], sender: 'Node'):
        """Receive and process alarm from another node, potentially forwarding via gossip."""
        # Pastikan ada message_id untuk tracking gossip & logging
        alarm_id = alarm.get('message_id') 
        if not alarm_id:
            # Beri ID unik jika tidak ada (seharusnya tidak terjadi jika alarm dibuat benar)
            alarm_id = f"recv_{self.node.id}_{sender.id}_{self.node.env.now}_{self.rng.randint(1000,9999)}"
            alarm['message_id'] = alarm_id 
            self.logger.warning(f"Received alarm from {sender.id} without 'message_id', assigned temporary ID: {alarm_id}")
            # Pertimbangkan: Abaikan alarm tanpa ID? Tergantung kebutuhan.

        self.logger.debug(f"Received alarm {alarm_id} from {sender.id}: Type {alarm.get('classification_text')}, Conf {alarm.get('assessment', {}).get('confidence')}")
        
        # Cek duplikat berdasarkan alarm_id
        if alarm_id in self.received_alarm_ids:
            self.logger.debug(f"Alarm {alarm_id} already received/processed, ignoring.")
            # Simpan event bahwa alarm ini diabaikan karena duplikat
            if self.node.db:
                self.node.db.store_event(
                    timestamp=self.node.env.now,
                    iteration=self.node.current_iteration,
                    node_id=self.node.id,
                    event_type='alarm_ignored_duplicate',
                    details={'original_alarm_id': alarm_id},
                    related_node_id=sender.id
                )
            return
            
        self.received_alarm_ids.add(alarm_id)

        try:
            # Fast-path: quarantine check
            if sender.id in getattr(self.node, 'quarantined_nodes', set()):
                self.logger.info(
                    "Ignoring alarm %s from node %s due to quarantine status.",
                    alarm_id,
                    sender.id,
                )
                if self.node.db:
                    self.node.db.store_event(
                        timestamp=self.node.env.now,
                        iteration=self.node.current_iteration,
                        node_id=self.node.id,
                        event_type='alarm_ignored_quarantine',
                        details={'alarm_id': alarm_id},
                        related_node_id=sender.id
                    )
                return

            # Evaluasi trust sender
            trust_score = self.node.evaluate_trust(sender)
            # Ambil threshold dari trust_config node; fallback aman jika tidak tersedia.
            trust_threshold = self.node.trust_config.get('trust_threshold', 0.5) if hasattr(self.node, 'trust_config') else 0.5

            if trust_score < trust_threshold:
                self.logger.info(
                    "Ignoring alarm %s from node %s due to low trust (%.3f < %.3f).",
                    alarm_id,
                    sender.id,
                    trust_score,
                    trust_threshold,
                )
                # Simpan event bahwa alarm diabaikan karena trust rendah
                if self.node.db:
                    self.node.db.store_event(
                        timestamp=self.node.env.now,
                        iteration=self.node.current_iteration,
                        node_id=self.node.id,
                        event_type='alarm_ignored_low_trust',
                        details={'alarm_id': alarm_id, 'sender_trust': trust_score},
                        related_node_id=sender.id
                    )
                return

            # Proses alarm valid: tambahkan ke list node
            self.node.alarms.append(alarm)
            # Track contribution from sender (accepted alarms only).
            if hasattr(self.node, 'contribution_counts'):
                current_count = self.node.contribution_counts.get(sender.id, 0)
                self.node.contribution_counts[sender.id] = current_count + 1
            self.logger.info(f"Accepted alarm {alarm_id} from trusted node {sender.id}.")

            try:
                payload_bytes = len(json.dumps(alarm).encode('utf-8'))
            except Exception:
                payload_bytes = 0
            metric_logger.log_message(
                iteration=getattr(self.node, 'current_iteration', 0),
                sender_id=sender.id,
                receiver_id=self.node.id,
                message_type='alarm_receive',
                direction='in',
                payload_bytes=payload_bytes,
                metadata={'alarm_id': alarm_id},
            )

            # Simpan event alarm diterima ke DB (menggunakan metode store_event baru)
            if self.node.db:
                self.node.db.store_event(
                    timestamp=self.node.env.now,
                    iteration=self.node.current_iteration,
                    node_id=self.node.id, # Node yang menerima
                    event_type='alarm_received',
                    details=alarm, # Simpan seluruh data alarm
                    related_node_id=sender.id # Node pengirim
                )

            # Forward alarm via Gossip jika belum max hops
            current_hops = alarm.get('gossip_hops', 0)
            max_hops = self.gossip.max_hops
            
            if current_hops < max_hops:
                 self.logger.debug(f"Forwarding alarm {alarm_id} via gossip (hops={current_hops+1})")
                 forward_alarm = alarm.copy()
                 # Hop count sudah diincrement di spread_alarm saat pengiriman awal
                 self.spread_alarm(forward_alarm) 
            else:
                 self.logger.debug(f"Alarm {alarm_id} reached max hops ({current_hops}), stopping gossip.")
                 # Simpan event bahwa gossip berhenti karena max hops
                 if self.node.db:
                     self.node.db.store_event(
                         timestamp=self.node.env.now,
                         iteration=self.node.current_iteration,
                         node_id=self.node.id,
                         event_type='gossip_stopped_max_hops',
                         details={'alarm_id': alarm_id, 'hops': current_hops},
                         related_node_id=sender.id
                     )

        except Exception as e:
            self.logger.error(f"Error processing received alarm {alarm_id} from {sender.id}: {e}")
            import traceback
            self.logger.error(traceback.format_exc()) 
